### ISSUE TITLE
Testers wanted

### ISSUE THREAD

**Issue by felixchenier** [felixchenier/limitedinteraction#1]
At the moment, Limited Interaction was tested on three systems (Windows 10, macOS Catalina and Linux Mint). It seems to do very well, but it is still fresh and new and I'd like to have some reports from testers. Thank you!

Tasks that would help me a lot:
-------------------------------
1. Install Limited Interaction (either using pip, conda or directly by cloning the github repository)
2. Launch python3 and try the commands shown in README.md
3. Report your success of failure on this issue, with your OS, python distribution and python version (for example: macOS Big Sur, Anaconda Python, Python 3.7.

Thank you

**Comment by felixchenier** [comment]
Works on:
- macOS Catalina, conda-forge, python 3.7 to 3.9
- Linux Mint, OS-Included python after installing tk (apt-get install tk), python 3.7
- Window 10, conda-forge, python 3.8

Does not work on:
- macOS Catalina, OS-included python (tkinter not working on the OS python)
- macOS Big Sur, OS-included python (tkinter not working on the OS python)

**Comment by taylorrobertss** [comment]
Works on VScode Python v3.7.9 with no issues

**Comment by felixchenier** [comment]
Thanks @taylorrobertss, seams promising 😃
What OS and python distribution (directly from python.org, anaconda, homebrew, etc) please?

**Comment by taylorrobertss** [comment]
Opps sorry! Windows 10 and python.org

**Comment by felixchenier** [comment]
@taylorrobertss Thank you!
